<?php
declare(strict_types=1);
require __DIR__ . '/budget-recommendations-test.php';
$full = travel_fund_month(0, 20000, 0, 100000, 100000);
check($full['available_cents'] === 20000, 'unused monthly travel money is available to carry forward');
$partial = travel_fund_month(40000, 20000, 0, 112000, 100000);
check($partial['available_cents'] === 48000 && $partial['reallocated_cents'] === 12000 && $partial['reserve_used_elsewhere_cents'] === 0, 'other overages consume this month’s travel contribution before old savings');
$allUsed = travel_fund_month(40000, 20000, 0, 160000, 100000);
check($allUsed['available_cents'] === 0 && $allUsed['reserve_used_elsewhere_cents'] === 40000, 'money used to make ends meet does not also carry forward');
$trip = travel_fund_month(60000, 20000, 75000, 100000, 100000);
check($trip['available_cents'] === 5000 && $trip['unfunded_cents'] === 0, 'accumulated funds cover a trip larger than one month’s contribution');
$over = travel_fund_month(10000, 20000, 40000, 105000, 100000);
check($over['available_cents'] === 0 && $over['unfunded_cents'] === 15000, 'overdrawn funds never create a negative carryover or hide unfunded spending');
$db->exec("INSERT INTO users (id, username) VALUES (35, 'travel_test'), (36, 'travel_other')");
$initial = budget_plan($db, 35, $month);
save_budget($db, 35, $month, ['misc' => '1000'], budget_form_version($initial));
$initial = budget_plan($db, 35, $month);
rejects(fn() => start_travel_fund($db, 35, $month, '-1', budget_form_version($initial)), 'negative opening travel balances rejected');
rejects(fn() => start_travel_fund($db, 35, $priorMonth, '0', budget_form_version($initial)), 'old unused budgets cannot silently become historical savings');
$futurePlan = budget_plan($db, 35, $future);
save_budget($db, 35, $future, ['misc' => '1000'], budget_form_version($futurePlan));
start_travel_fund($db, 35, $month, '400', budget_form_version($initial));
check(count(budget_plan($db, 35, $future)['groups']) === 2, 'starting rollover also separates Travel in previously saved future budgets');
analyzer_query($db, 'DELETE FROM analyzer_budgets WHERE user_id = 35 AND month = ?', [$future]);
$plan = budget_plan($db, 35, $month);
$travelKey = array_key_first($plan['groups']); $travelCategory = $plan['groups'][$travelKey]['category_id'];
check($plan['groups'][$travelKey]['name'] === 'Travel' && $plan['targets'][$travelKey] === 0 && $plan['targets']['misc'] === 100000, 'starting a fund separates Travel from Misc without inventing a contribution');
rejects(fn() => start_travel_fund($db, 35, $month, '400', budget_form_version($plan)), 'opening savings cannot be added a second time');
check(travel_fund_balance($db, 36, $month) === null, 'travel balances are isolated by user');
save_budget($db, 35, $month, [$travelKey => '200', 'misc' => '1000'], budget_form_version($plan));
save_import($db, 35, pending_csv("Date,Name,Amount\n$month-01,COSTCO,-1250\n"));
$balance = travel_fund_balance($db, 35, $month);
check($balance['available_cents'] === 35000 && $balance['reallocated_cents'] === 25000 && $balance['reserve_used_elsewhere_cents'] === 5000, 'recorded purchases draw from current contribution and then saved funds');
$progress = budget_progress($db, 35, $month);
check($progress['groups'][$travelKey]['available_cents'] === 35000 && array_sum(array_column($progress['groups'], 'available_cents')) === $progress['total']['available_cents'], 'displayed category availability accounts for transferred travel funds and reconciles');
$futureBalance = travel_fund_balance($db, 35, $future);
check($futureBalance['opening_cents'] === 35000, 'future planning deducts already used savings without banking an unfinished month’s unused contribution');
$rec = recommend_for_test($db, 35, $month, '1000', '0', [$travelKey => 'cut_first', 'misc' => 'protect'], [$travelKey => '', 'misc' => ''])['proposal'];
$progress = budget_progress($db, 35, $month);
check(array_sum(array_column($progress['groups'], 'target_cents')) === $progress['total']['target_cents'], 'transfers still reconcile when the saved plan exceeds the cash limit');
// Model a fund that began three ended months ago using an explicit synthetic opening balance.
$start = $date->modify('-3 months')->format('Y-m');
$second = $date->modify('-2 months')->format('Y-m');
$third = $date->modify('-1 month')->format('Y-m');
$db->exec('DELETE FROM analyzer_budget_resources WHERE user_id = 35');
$db->exec('DELETE FROM analyzer_transactions WHERE user_id = 35');
$db->exec('DELETE FROM analyzer_budget_snapshots WHERE user_id = 35');
analyzer_query($db, 'UPDATE analyzer_travel_funds SET start_month = ?, opening_cents = 0 WHERE user_id = 35', [$start]);
analyzer_query($db, 'UPDATE analyzer_budgets SET month = ? WHERE user_id = 35', [$start]);
$card = (int) user_accounts($db, 35)[0]['id'];
save_import($db, 35, pending_csv("Date,Name,Amount\n$start-01,COSTCO,-1000\n$second-01,COSTCO,-1100\n$third-01,COSTCO,-1000\n$month-01,TRAVEL TRIP,-650\n", $card));
foreach (monthly_report($db, 35, $month)['merchants'] as $merchant) { update_merchant($db, 35, (int) $merchant['id'], 'Travel trip', $travelCategory, ''); }
$balance = travel_fund_balance($db, 35, $month);
check($balance['opening_cents'] === 50000 && $balance['available_cents'] === 5000 && $balance['ledger'][1]['reallocated_cents'] === 10000, 'three-month ledger carries only leftovers and covers a later lump-sum trip');
$progress = budget_progress($db, 35, $month);
check($progress['groups'][$travelKey]['status'] !== 'over', 'funded travel does not show as over budget on the analyzer');
$rec = recommend_for_test($db, 35, $month, '1200', '0', [$travelKey => 'cut_first', 'misc' => 'protect'], [$travelKey => '', 'misc' => ''])['proposal'];
check($rec['groups'][$travelKey]['floor_cents'] === 15000, 'recommendations use prior travel savings without charging the whole trip to new income');
// A late purchase consumes a past contribution rather than leaving the old balance cached.
save_import($db, 35, pending_csv("Date,Name,Amount\n$start-02,COSTCO,-200\n", $card));
check(travel_fund_balance($db, 35, $month)['opening_cents'] === 30000, 'late imported overages reduce later carryover');
analyzer_query($db, 'DELETE FROM analyzer_transactions WHERE user_id = 35 AND transaction_date LIKE ?', [$third . '%']);
$balance = travel_fund_balance($db, 35, $month);
check($balance['opening_cents'] === 10000 && in_array($third, $balance['missing_months'], true), 'missing months do not create fictitious travel savings');
echo "All travel rollover checks passed.\n";
