<?php if (!defined('DAN_PORTAL')) { http_response_code(403); exit; } ?>
<section class="panel budget-recommendation" id="recommended-budget" aria-labelledby="recommendation-heading">
    <div class="section-heading"><div><div class="eyebrow">MAKE YOUR MONTH FIT</div><h2 id="recommendation-heading">Your recommended budget</h2></div><span class="pill">You choose when to switch</span></div>
    <p>Tell us what’s available for the month. We’ll build a plan around your spending patterns and show where changes would help it fit.</p>
    <?php if ($budgetMonth >= recommendation_current_month()): ?>
    <?php if ($vacationFund): ?><p class="hint">We’ll reserve <?= money($vacationFund['planned_contribution_cents']) ?> for your Vacation Fund before allocating expense targets. Enter any additional savings or cushion below.</p><?php endif; ?>
    <form method="post" action="/?page=budget" class="recommendation-form">
        <?php csrf_field(); ?><input type="hidden" name="action" value="recommend_budget"><input type="hidden" name="budget_month" value="<?= escape($budgetMonth) ?>"><input type="hidden" name="budget_version" value="<?= escape(budget_form_version($budget)) ?>"><input type="hidden" name="resources_version" value="<?= escape(budget_resources_version($budgetResources)) ?>">
        <div class="recommendation-inputs">
            <div><label for="cash-available">Monthly cash available · USD</label><input type="text" inputmode="decimal" id="cash-available" name="cash_available" maxlength="16" required placeholder="e.g. 2000" value="<?= escape(is_string($resourceValues['cash_available'] ?? null) ? $resourceValues['cash_available'] : ($budgetResources ? number_format($budgetResources['cash_cents'] / 100, 2, '.', '') : '')) ?>" aria-describedby="cash-help"></div>
            <div><label for="cash-reserve">Other savings or cushion (excluding Vacation Fund) · USD</label><input type="text" inputmode="decimal" id="cash-reserve" name="cash_reserve" maxlength="16" required value="<?= escape(is_string($resourceValues['cash_reserve'] ?? null) ? $resourceValues['cash_reserve'] : number_format(($budgetResources['reserve_cents'] ?? 0) / 100, 2, '.', '')) ?>"></div>
        </div>
        <p class="hint" id="cash-help">Use take-home pay after commitments paid outside these categories, such as rent, healthcare or debt payments. If an expense is already included in a category here, don’t subtract it again. This is a monthly plan; payday and bill timing still matter.</p>
        <?php if ($budgetResources && $budgetResources['month'] !== $budgetMonth): ?><p class="hint">Cash inputs carried forward from <?= escape(month_label($budgetResources['month'])) ?>. Update them if your situation changed.</p><?php endif; ?>
        <details class="recommendation-priorities"><summary>Priorities &amp; minimums <span class="muted">Choose where there’s room to cut</span></summary>
            <p class="hint">Essentials and mixed or unfamiliar categories start protected. “Protect” keeps the planning baseline unless you enter a minimum. Other categories can reduce toward zero or your chosen minimum. Spending already recorded this month is protected; Vacation Fund contributions are reserved separately before allocating expense targets. Change these choices to fit your needs.</p>
            <?php foreach ($budget['groups'] as $key => $group):
                $pref = $budgetResources['preferences'][$key] ?? ['priority' => budget_default_priority($group['name']), 'minimum_cents' => null];
                $priority = is_string($resourceValues['priorities'][$key] ?? null) ? $resourceValues['priorities'][$key] : $pref['priority'];
                $minimum = is_string($resourceValues['minimums'][$key] ?? null) ? $resourceValues['minimums'][$key] : ($pref['minimum_cents'] === null ? '' : number_format($pref['minimum_cents'] / 100, 2, '.', '')); ?>
            <div class="recommendation-priority-row"><strong><?= escape($group['name']) ?></strong>
                <div><label class="sr-only" for="priority-<?= escape($key) ?>"><?= escape($group['name']) ?> priority</label><select name="priorities[<?= escape($key) ?>]" id="priority-<?= escape($key) ?>"><?php foreach (['protect' => 'Protect', 'flexible' => 'Flexible', 'cut_first' => 'Cut first'] as $choice => $label): ?><option value="<?= $choice ?>" <?= $priority === $choice ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div>
                <div><label class="sr-only" for="minimum-<?= escape($key) ?>"><?= escape($group['name']) ?> minimum · USD</label><input type="text" inputmode="decimal" name="minimums[<?= escape($key) ?>]" id="minimum-<?= escape($key) ?>" placeholder="Minimum $ · auto" maxlength="16" value="<?= escape($minimum) ?>"></div>
            </div><?php endforeach; ?>
        </details>
        <p class="hint">Building a plan saves these inputs for this month onward. Category totals, cash inputs, priorities and recent merchant summaries are used for the AI explanation.</p>
        <button type="submit">Build recommended budget</button>
    </form>
    <?php else: ?><p class="hint">Choose this month or a future month to build a new recommendation. Past budgets stay as they were.</p><?php endif; ?>
    <?php if ($budgetRecommendation): $proposal = $budgetRecommendation['proposal']; $advice = $budgetRecommendation['advice']; ?>
    <div class="recommendation-result">
        <?php if (($proposal['vacation_contribution_cents'] ?? 0) !== ($vacationFund['planned_contribution_cents'] ?? 0) || (($proposal['travel_fund']['kind'] ?? '') !== ($vacationFund['kind'] ?? '') && $vacationFund)): ?><p class="notice">Your Vacation Fund changed since this recommendation. Build a fresh recommendation to include the current contribution; the figures below describe the earlier plan.</p><?php endif; ?>
        <?php if (!empty($proposal['vacation_contribution_cents'])): ?><p class="hint">Vacation Fund contribution: <?= money($proposal['vacation_contribution_cents']) ?>. This is separate from the expense targets below. Cash left for expenses: <?= money($proposal['capacity_cents']) ?>.</p><?php endif; ?>
        <?php if ($budgetRecommendation['applied_at']): ?><p class="notice">This recommendation was applied. The current targets above are your active budget.</p>
        <?php elseif ($budgetRecommendation['stale']): ?><p class="notice">Your spending, cash inputs or budget changed. Build a fresh recommendation before switching.</p><?php endif; ?>
        <div class="recommendation-metrics"><div><span>Cash available</span><strong><?= money($proposal['cash_cents']) ?></strong></div><div><span>Kept aside</span><strong><?= money($proposal['reserve_cents']) ?></strong></div><div><span>Spending limit</span><strong><?= money($proposal['capacity_cents']) ?></strong></div><div><span>Recommended targets</span><strong><?= money($proposal['recommended_total_cents']) ?></strong></div></div>
        <?php if ($proposal['status'] === 'needs_history'): ?><p class="notice">We need past spending or a starting budget before making a useful recommendation. Import some history or set your current targets above.</p>
        <?php elseif ($proposal['status'] === 'shortfall'): ?><p class="notice"><strong>The protected amounts need <?= money($proposal['shortfall_cents']) ?> more than you have available.</strong> This plan does not fit yet. Check your cash inputs and minimums, review flexible commitments, or consider whether more income is needed. We haven’t lowered protected costs to pretend the numbers work.</p>
        <?php elseif ($proposal['historical_gap_cents'] > 0): ?><p><strong>Your usual pattern needs about <?= money($proposal['historical_gap_cents']) ?> more than the spending limit.</strong> The recommended amounts below require cuts. Categories marked “Cut first” take the first reductions.</p>
        <?php else: ?><p>Your planning baseline fits within your available cash. Extra room stays available rather than increasing every category.</p><?php endif; ?>
        <?php if ($proposal['unallocated_cents'] > 0 && $proposal['status'] !== 'needs_history'): ?><p class="hint"><?= money($proposal['unallocated_cents']) ?> remains unallocated, in addition to the <?= money($proposal['reserve_cents']) ?> kept aside.</p><?php endif; ?>
        <div class="table-scroll"><table class="recommendation-table"><thead><tr><th>Category</th><th class="number">Planning baseline</th><th class="number">Current budget</th><th class="number">Recommended</th></tr></thead><tbody>
        <?php foreach ($proposal['groups'] as $key => $group): ?><tr><th scope="row"><?= escape($group['name']) ?><small><?= escape(budget_recommendation_reason($group)) ?><?php if ($group['cut_percent'] >= 50): ?> This is a substantial change from past spending.<?php endif; ?><?php if ($group['smoothed']): ?> A large past month was smoothed; check upcoming costs.<?php endif; ?></small></th><td class="number"><?= money($group['baseline_cents']) ?></td><td class="number"><?= !isset($budget['targets'][$key]) ? 'Not set' : money($budget['targets'][$key]) ?></td><td class="number"><strong><?= money($group['recommended_cents']) ?></strong></td></tr><?php endforeach; ?>
        </tbody><tfoot><tr><th>Total</th><td class="number"><?= money($proposal['baseline_cents']) ?></td><td class="number"><?= $budget['targets'] ? money(array_sum($budget['targets'])) : 'Not set' ?></td><td class="number"><?= money($proposal['recommended_total_cents']) ?></td></tr></tfoot></table></div>
        <?php if (!$budgetRecommendation['applied_at'] && !$budgetRecommendation['stale'] && $proposal['status'] === 'ready' && $budgetMonth >= recommendation_current_month()): ?>
        <form method="post" action="/?page=budget" class="recommendation-apply"><?php csrf_field(); ?><input type="hidden" name="action" value="apply_recommended_budget"><input type="hidden" name="budget_month" value="<?= escape($budgetMonth) ?>"><input type="hidden" name="recommendation_version" value="<?= escape($proposal['fingerprint']) ?>"><button type="submit">Apply recommended budget</button><span class="hint">Replaces <?= escape(month_label($budgetMonth)) ?> targets and carries forward until your next saved change.</span></form>
        <?php endif; ?>
        <?php if ($advice): ?><div class="recommendation-take"><h3>KLE Coin’s Take</h3><details class="review-disclosure"><summary><span class="review-teaser-text"><?= escape(month_review_teaser($advice['summary'])) ?></span> <span class="review-toggle"><svg class="review-target" viewBox="0 0 28 28" width="22" height="22" aria-hidden="true"><circle cx="12" cy="16" r="10" fill="#ffe58a" stroke="currentColor" stroke-width="1.6"/><circle cx="12" cy="16" r="6" fill="none" stroke="currentColor" stroke-width="1.6"/><circle cx="12" cy="16" r="2" fill="currentColor"/><path d="M25 3 12 16m0-5v5h5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg><span class="review-read-more">Read now</span><span class="review-read-less">Read less</span><span class="sr-only"> about your recommended budget</span></span></summary><?php if (month_review_teaser($advice['summary']) !== $advice['summary']): ?><p><?= escape($advice['summary']) ?></p><?php endif; ?><ul><?php foreach ($advice['next_steps'] as $step): ?><li><?= escape($step) ?></li><?php endforeach; ?></ul><details><summary>Why each category changed</summary><?php foreach ($proposal['groups'] as $key => $group): ?><p><strong><?= escape($group['name']) ?>.</strong> <?= escape($advice['categories'][$key]) ?></p><?php endforeach; ?></details><p class="hint">AI-assisted explanation of this saved recommendation.</p></details></div>
        <?php elseif ($budgetRecommendation['ai_status'] === 'failed'): ?><p class="hint">The personalized explanation is unavailable. The calculated plan and category reasons above are ready to review.</p>
        <?php elseif (in_array($budgetRecommendation['ai_status'], ['pending', 'processing'], true) && category_ai_config()['enabled']): ?><p class="hint">Your personalized take is being prepared. The numbers are ready to review. <a href="/?page=budget&amp;month=<?= escape($budgetMonth) ?>#recommended-budget">Refresh</a></p><?php endif; ?>
        <p class="hint"><?php if (count($proposal['months']) < 3): ?>Limited history: <?php endif; ?><?= count($proposal['months']) ?> earlier month<?= count($proposal['months']) === 1 ? '' : 's' ?> used<?= $proposal['months'] ? ', ' . escape(month_label($proposal['months'][0])) . '–' . escape(month_label($proposal['months'][array_key_last($proposal['months'])])) : '' ?>. <?= $proposal['confirmed_count'] ?> confirmed complete.<?php if ($proposal['confirmed_count'] < count($proposal['months'])): ?> Unconfirmed history may be partial.<?php endif; ?></p>
    </div>
    <?php endif; ?>
    <details class="data-note"><summary>How we build the recommendation</summary><p>Everyday categories blend the last six available months: 70% of a recent-weighted average and 30% of the median. With at least four months, unusually large months are capped for this calculation. Travel and home improvement use up to twelve months of average spending so occasional costs still have an allowance. Travel targets cover ordinary purchases. Set a separate Vacation Fund contribution above to save for future vacations. Its planned contribution is reserved before allocating expense targets, and accumulated savings are not treated as new monthly cash. Missing months are excluded, and confirmed zero-activity months count. Purchases are used before refunds; card payments are excluded.</p><p>We reduce “Cut first” categories proportionally, then “Flexible”, then any room above a protected minimum. We never go below a minimum or spending already recorded for the selected month. This is a suggested monthly plan, not a prediction. Review the assumptions and minimums before switching.</p></details>
</section>
