<?php if (!defined('DAN_PORTAL')) { http_response_code(403); exit; } ?>
<div class="page-heading"><div><div class="eyebrow">LESS UPLOADING, MORE CLARITY</div><h1>Connect your credit card.</h1><p class="page-intro">Bring posted transactions into your spending reports automatically.</p></div><span class="pill">SimpleFIN Bridge</span></div>
<?php if (!$sfin): ?>
<section class="panel connect-steps"><h2>Three steps to automatic imports</h2>
<ol><li><strong>Connect your card in SimpleFIN.</strong><p>Open SimpleFIN, create your account, and search for <strong>Cardmember Service – Elan Financial Services</strong>. Complete the connection for your Fidelity Rewards Visa there.</p><a class="button secondary" href="https://bridge.simplefin.org/" target="_blank" rel="noopener noreferrer">Open SimpleFIN ↗</a></li>
<li><strong>Create a setup token.</strong><p>In SimpleFIN, create an app connection for KLE Coin and copy its setup token. Your bank password stays with the connection provider.</p><a href="https://bridge.simplefin.org/simplefin/create" target="_blank" rel="noopener noreferrer">Create a SimpleFIN setup token ↗</a></li>
<li><strong>Connect it here, then select your card.</strong><form method="post" action="/?page=connect"><?php csrf_field(); ?><input type="hidden" name="action" value="sfin_connect"><label for="setup-token">SimpleFIN setup token</label><input type="password" id="setup-token" name="setup_token" autocomplete="off" maxlength="4096" required><p class="hint">This token is used once. The resulting access credential stays privately on the server.</p><button type="submit">Connect SimpleFIN</button></form></li></ol>
<p class="hint">SimpleFIN has its own subscription. Verify the Elan connection there before enabling imports here. Updates are generally daily, depending on the institution.</p></section>
<?php else: ?>
<section class="panel"><div class="section-heading"><div><div class="eyebrow"><?= $sfin['demo'] ? 'DEMO · PREVIEW ONLY' : 'CONNECTED' ?></div><h2><?= $sfinLink && $sfinLink['enabled'] ? 'Automatic imports are on.' : 'Choose what to bring into your reports.' ?></h2></div><?php if ($sfinLink): ?><a href="<?= escape(analyzer_url('', (int) $sfinLink['account_id'])) ?>">View card reports ↗</a><?php endif; ?></div>
<?php if ($sfin['message']): ?><p class="notice"><?= escape($sfin['message']) ?></p><?php endif; ?>
<?php foreach ($sfin['snapshot']['errors'] ?? [] as $message): ?><p class="error"><?= escape($message) ?></p><?php endforeach; ?>
<?php if ($sfinLink): ?><p><strong><?= escape($sfinLink['label']) ?></strong> · Imports from <?= escape($sfinLink['start_date']) ?> · <?= $sfinLink['enabled'] ? 'Active' : 'Paused' ?></p><?php endif; ?>
<p class="hint">Last successful retrieval: <?= $sfin['last_success'] ? escape($sfin['last_success']) : 'Not yet' ?>. When enabled, the app checks about every six hours. New data depends on the bank’s update schedule. Only posted USD transactions are imported.</p>
<div class="actions"><form method="post" action="/?page=connect"><?php csrf_field(); ?><input type="hidden" name="action" value="sfin_refresh"><button type="submit" class="secondary">Refresh connection</button></form>
<?php if ($sfinLink): ?><form method="post" action="/?page=connect"><?php csrf_field(); ?><input type="hidden" name="action" value="<?= $sfinLink['enabled'] ? 'sfin_pause' : 'sfin_resume' ?>"><button type="submit" class="secondary"><?= $sfinLink['enabled'] ? 'Pause imports' : 'Resume imports' ?></button></form><?php endif; ?></div>
<p class="hint">Manual refresh is limited to once per hour to respect SimpleFIN’s request limits.</p>
</section>
<?php if ($sfin['snapshot'] && (!$sfinLink || !$sfinLink['enabled']) && !$sfin['demo']): ?>
<section class="panel"><h2>Select your credit card</h2><p class="hint">SimpleFIN may return several account types. Choose the Elan credit card only. Match it to the card you already uploaded, if applicable.</p>
<form method="post" action="/?page=connect" class="connection-form"><?php csrf_field(); ?><input type="hidden" name="action" value="sfin_enable">
<label for="remote-account">Account from SimpleFIN</label><select name="remote_key" id="remote-account" required><option value="">Choose your credit card</option><?php foreach ($sfin['snapshot']['accounts'] as $account): ?><option value="<?= escape(simplefin_remote_key($account)) ?>" <?= ($account['currency'] ?? '') !== 'USD' ? 'disabled' : '' ?>><?= escape(($account['conn_name'] ?? $account['org']['name'] ?? 'Connected institution') . ' · ' . $account['name'] . ' · ' . $account['currency']) ?></option><?php endforeach; ?></select>
<label for="local-account">Card in this app</label><select id="local-account" name="account_id"><option value="0">Create a new card (no previous CSV uploads)</option><?php foreach ($sfinAccounts as $account): ?><option value="<?= (int) $account['id'] ?>"><?= escape($account['label']) ?><?= $account['last_date'] ? ' · history through ' . escape($account['last_date']) : '' ?></option><?php endforeach; ?></select>
<label for="card-label">New card name (only when creating a card)</label><input id="card-label" name="account_label" maxlength="80" placeholder="Fidelity Rewards Visa">
<label for="sync-start">Import posted transactions from</label><input type="date" id="sync-start" name="start_date" min="<?= gmdate('Y-m-d', time() - 44 * 86400) ?>" max="<?= gmdate('Y-m-d', time() + 86400) ?>" value="<?= gmdate('Y-m-d') ?>" required>
<p class="hint">For an existing card, choose the day after its latest imported transaction. This keeps CSV history and automatic imports from overlapping. Available bank history varies; at most 44 days can be requested initially. Choose the first posted date not covered by your CSV; purchase dates can differ. Dates use the provider’s posted timestamp in UTC.</p>
<button type="submit">Enable automatic imports</button></form></section>
<?php endif; ?>
<?php if ($sfin['snapshot']): ?><section class="panel"><h2>Available accounts</h2><p class="hint">Inspect the account and sample activity before selecting it. Pending items are preview-only.<?= $sfin['demo'] ? ' Demo data cannot be imported into your reports.' : '' ?></p>
<?php foreach ($sfin['snapshot']['accounts'] as $account): ?><details class="preview-details"><summary><?= escape($account['name']) ?> · <?= escape($account['currency']) ?> · <?= count($account['transactions'] ?? []) ?> transactions</summary><div class="table-scroll"><table><thead><tr><th>Posted date (UTC)</th><th>Description</th><th class="number">Amount</th><th>Status</th></tr></thead><tbody><?php foreach (array_slice($account['transactions'] ?? [], -20) as $transaction): ?><tr><td><?= !empty($transaction['posted']) ? gmdate('Y-m-d', (int) $transaction['posted']) : 'Not posted' ?></td><td><?= escape((string) ($transaction['description'] ?? '')) ?></td><td class="number"><?= escape((string) ($transaction['amount'] ?? '')) ?> <?= escape($account['currency']) ?></td><td><?= !empty($transaction['pending']) ? 'Pending' : 'Posted' ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endforeach; ?></section><?php endif; ?>
<section class="panel"><details><summary>Disconnect SimpleFIN</summary><p class="hint">Stops this app’s imports and removes its stored credential. Existing transactions and reports remain. You should also revoke the app token in your SimpleFIN account.</p><form method="post" action="/?page=connect"><?php csrf_field(); ?><input type="hidden" name="action" value="sfin_disconnect"><button type="submit" class="secondary">Disconnect from this app</button></form></details></section>
<?php endif; ?>
