<?php if (!defined('DAN_PORTAL')) { http_response_code(403); exit; } ?>
<section class="panel travel-fund-panel" aria-labelledby="travel-fund-heading">
    <div class="section-heading"><div><div class="eyebrow">SAVE NOW, GO LATER</div><h2 id="travel-fund-heading">Your travel fund</h2></div><span class="pill">Unused money rolls forward</span></div>
    <?php if ($travelFund): ?>
    <div class="recommendation-metrics"><div><span>Carried into this month</span><strong><?= money($travelFund['opening_cents']) ?></strong></div><div><span>This month’s contribution</span><strong><?= money($travelFund['contribution_cents']) ?></strong></div><div><span>Travel spending</span><strong><?= money($travelFund['spent_cents']) ?></strong></div><div><span>Still available</span><strong><?= money($travelFund['available_cents']) ?></strong></div></div>
    <p><?php if ($travelFund['reallocated_cents'] > 0): ?><strong><?= money($travelFund['reallocated_cents']) ?> went toward overages in other categories.</strong> That money is no longer in the travel fund and will not carry forward.<?php else: ?>No travel money has been needed to cover other category overages this month.<?php endif; ?></p>
    <p class="hint">Set your monthly contribution using the Travel target above. A trip can use that contribution plus money carried forward, so funded travel doesn’t count as blowing this month’s budget. The balance updates with recorded spending; refunds and card payments are excluded. Keep this money set aside in your own account—this page does not move it.</p>
    <?php if ($travelFund['unconfirmed_months'] || $travelFund['missing_months']): ?><p class="hint">Some earlier history is unconfirmed or missing. Missing months add no savings. Late transactions can reduce the balance.</p><?php endif; ?>
    <?php if ($travelFund['ledger']): ?><details class="data-note"><summary>Travel fund history</summary><div class="table-scroll"><table><thead><tr><th>Month</th><th class="number">Opening</th><th class="number">Added</th><th class="number">Travel</th><th class="number">Used elsewhere</th><th class="number">Carried forward</th></tr></thead><tbody><?php foreach ($travelFund['ledger'] as $entry): ?><tr><th scope="row"><?= escape(month_label($entry['month'])) ?></th><?php foreach (['opening_cents', 'contribution_cents', 'spent_cents', 'reallocated_cents', 'available_cents'] as $field): ?><td class="number"><?= money($entry[$field]) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
    <?php elseif ($travelFundSetting): ?><p>Your travel fund starts in <?= escape(month_label($travelFundSetting['start_month'])) ?> with <?= money((int) $travelFundSetting['opening_cents']) ?> already set aside.</p>
    <?php elseif ($budgetMonth >= recommendation_current_month() && $budget['source_month']): ?>
    <p>Let unused Travel targets build up for a future trip. Other category overages use that money first when it’s needed to make the overall budget balance; only what’s left carries forward.</p>
    <form method="post" action="/?page=budget" class="travel-start-form"><?php csrf_field(); ?><input type="hidden" name="action" value="start_travel_fund"><input type="hidden" name="budget_month" value="<?= escape($budgetMonth) ?>"><input type="hidden" name="budget_version" value="<?= escape(budget_form_version($budget)) ?>">
        <label for="travel-opening">Money already set aside before <?= escape(month_label($budgetMonth)) ?> · USD</label><input type="text" inputmode="decimal" id="travel-opening" name="travel_opening" value="0" maxlength="16" required>
        <label class="coverage-confirm"><input type="checkbox" name="travel_confirmed" value="1" required> This is money I actually set aside, separate from this month’s cash available.</label>
        <p class="hint">Starts in <?= escape(month_label($budgetMonth)) ?>; old unused targets are not assumed to be savings. If Travel is currently in Misc, it becomes a separate target starting at $0 so you can choose a contribution.</p>
        <button type="submit">Start travel rollover</button>
    </form>
    <?php else: ?><p class="hint">Save a budget for this month or a future month to start a travel fund. You can then enter money already saved and choose a monthly contribution.</p><?php endif; ?>
</section>
