<?php if (!defined('DAN_PORTAL')) { http_response_code(403); exit; } ?>
<section class="panel travel-fund-panel" aria-labelledby="vacation-fund-heading">
    <div class="section-heading"><div><div class="eyebrow">SAVE NOW, GO LATER</div><h2 id="vacation-fund-heading">Vacation Fund</h2></div><span class="pill">Savings that carry forward</span></div>
    <p>Travel is your monthly expense category. Vacation Fund is money you set aside separately and build up over time. A Travel purchase within your overall spending allowance does not reduce this fund.</p>
    <?php if ($vacationFund): $fund = $vacationFund; ?>
    <div class="recommendation-metrics">
        <div><span>Carried into this month</span><strong><?= money($fund['opening_cents']) ?></strong></div>
        <div><span><?= $fund['provisional'] ? 'Contribution · provisional' : 'Contribution' ?></span><strong><?= money($fund['contribution_cents']) ?></strong></div>
        <div><span><?= $fund['provisional'] ? 'Shortage draw · provisional' : 'Used for monthly shortage' ?></span><strong><?= money($fund['reallocated_cents']) ?></strong></div>
        <div><span><?= $fund['provisional'] ? 'Balance · provisional' : 'Closing balance' ?></span><strong><?= money($fund['available_cents']) ?></strong></div>
    </div>
    <p class="hint">Opening balance + monthly contribution − monthly shortage draw = remaining Vacation Fund. Expense targets do not reduce your contribution. Unused budget across all expense categories offsets overspending before this fund is touched. When monthly cash is entered, any additional unallocated cash also covers spending first. A draw starts only after total purchases exceed <?= money($fund['expense_capacity_cents']) ?>, using this month’s contribution first, then accumulated savings.</p>
    <?php if ($fund['planning_gap_cents'] > 0): ?><p class="notice">Your expense targets plus planned contribution exceed your monthly cash after other savings by <?= money($fund['planning_gap_cents']) ?>. This planning gap does not reduce your Vacation Fund. Review your targets or cash inputs; a draw only occurs after recorded spending exhausts the overall expense budget.</p><?php endif; ?>
    <?php if ($fund['planned_contribution_cents'] > $fund['contribution_cents']): ?><p class="notice">Planned contribution: <?= money($fund['planned_contribution_cents']) ?>. No contribution is included for this month because its budget or spending history is missing.</p><?php endif; ?>
    <?php if ($fund['unfunded_cents'] > 0): ?><p class="notice">The fund cannot cover the full shortage. <?= money($fund['unfunded_cents']) ?> remains uncovered.</p><?php endif; ?>
    <?php if ($fund['provisional']): ?><p class="hint">This is a running estimate using recorded purchases. Month-end figures remain provisional until the month is confirmed complete. Late transactions can change the balance.</p><?php endif; ?>
    <?php if ($fund['unconfirmed_months'] || $fund['missing_months']): ?><p class="hint">Some earlier history is unconfirmed or missing. Missing months add no savings. Late transactions can reduce carried balances.</p><?php endif; ?>
    <?php if ($fund['ledger']): ?><details class="data-note"><summary>Vacation Fund history</summary><div class="table-scroll"><table><thead><tr><th>Month</th><th class="number">Opening</th><th class="number">Added</th><th class="number">Shortage draw</th><th class="number">Carried forward</th></tr></thead><tbody><?php foreach ($fund['ledger'] as $entry): ?><tr><th scope="row"><?= escape(month_label($entry['month'])) ?><?= $entry['provisional'] ? ' · provisional' : '' ?></th><?php foreach (['opening_cents', 'contribution_cents', 'reallocated_cents', 'available_cents'] as $field): ?><td class="number"><?= money($entry[$field]) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
    <?php elseif ($vacationSetting): ?><p>Your Vacation Fund starts in <?= escape(month_label($vacationSetting['start_month'])) ?> with <?= money((int) $vacationSetting['opening_cents']) ?> already set aside.</p>
    <?php elseif ($travelFundSetting): ?><p class="notice">You have an existing travel rollover fund. Confirm the money carried into this month below to switch to a separate Vacation Fund. Earlier travel rollover history stays intact. Your existing Travel target will become an ordinary expense allowance; review it above.</p><?php endif; ?>
    <?php if (!$vacationFund && $travelFund): ?><details class="data-note"><summary>Legacy travel rollover for <?= escape(month_label($budgetMonth)) ?></summary><p><?= money($travelFund['opening_cents']) ?> carried in + <?= money($travelFund['contribution_cents']) ?> contribution − <?= money($travelFund['spent_cents']) ?> Travel purchases − <?= money($travelFund['reallocated_cents']) ?> used elsewhere = <?= money($travelFund['available_cents']) ?> remaining under the earlier travel rollover rules.</p></details><?php endif; ?>
    <?php if ($budget['source_month'] && $budgetMonth >= recommendation_current_month() && (!$vacationSetting || $budgetMonth >= $vacationSetting['start_month'])): ?>
    <form method="post" action="/?page=budget" class="travel-start-form">
        <?php csrf_field(); ?><input type="hidden" name="action" value="save_vacation_fund"><input type="hidden" name="budget_month" value="<?= escape($budgetMonth) ?>"><input type="hidden" name="budget_version" value="<?= escape(budget_form_version($budget)) ?>"><input type="hidden" name="vacation_version" value="<?= escape($vacationVersion ?? '') ?>">
        <?php if (!$vacationSetting): ?>
        <label for="vacation-opening">Money already saved before <?= escape(month_label($budgetMonth)) ?> · USD</label><input type="text" inputmode="decimal" id="vacation-opening" name="vacation_opening" value="<?= escape(is_string($vacationValues['vacation_opening'] ?? null) ? $vacationValues['vacation_opening'] : number_format(($travelFund['opening_cents'] ?? 0) / 100, 2, '.', '')) ?>" maxlength="16" required>
        <label class="coverage-confirm"><input type="checkbox" name="vacation_confirmed" value="1" required<?= ($vacationValues['vacation_confirmed'] ?? '') === '1' ? ' checked' : '' ?>> This is money already set aside, separate from this month’s cash available.</label>
        <?php endif; ?>
        <label for="vacation-contribution">Monthly Vacation Fund contribution · USD</label><input type="text" inputmode="decimal" id="vacation-contribution" name="vacation_contribution" value="<?= escape(is_string($vacationValues['vacation_contribution'] ?? null) ? $vacationValues['vacation_contribution'] : number_format(($vacationFund['planned_contribution_cents'] ?? 0) / 100, 2, '.', '')) ?>" maxlength="16" required>
        <p class="hint">Applies from <?= escape(month_label($budgetMonth)) ?> until your next saved change. Enter 0 to pause contributions and keep the accumulated balance. If Travel is in Misc, starting the fund gives it a separate $0 expense target for you to adjust.</p>
        <button type="submit"><?= $vacationSetting ? 'Save Vacation Fund contribution' : 'Start Vacation Fund' ?></button>
    </form>
    <?php elseif (!$vacationSetting): ?><p class="hint">Save a budget for this month or a future month to start your Vacation Fund.</p><?php endif; ?>
    <p class="hint">This tracks money you set aside in your own account; it does not transfer bank funds. Contributions are savings, not expenses. Refunds and card payments are excluded from spending, as elsewhere in your budget.</p>
</section>
